
language: ruby

matrix:
  include:
    - os: osx
      osx_image: xcode11
  fast_finish: true

env:
  global: |
      export PATH="/usr/local/opt/ccache/libexec:$PATH"
      CODECOV_TOKEN=4bd3d3ee-ecc8-4130-90d7-276626099dc4
      PATH=${PATH}:${HOME}/kcov/bin

before_install: |
  wget https://github.com/SimonKagstrom/kcov/archive/master.zip
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  brew update && brew install jq && pip3 install awscli

install: |
  unzip -a master.zip && cd kcov-master && mkdir build && cd build
  cmake -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DCMAKE_INSTALL_PREFIX=${HOME}/kcov ..
  make && make install && cd ../.. && rm -rf kcov-master && mkdir -p coverage

script: |
  kcov coverage awscli.sh

after_success: |
  bash <(curl -s https://codecov.io/bash)
