addons:
  apt:
    packages:
      - binutils-dev
      - libcurl4-openssl-dev
      - libdw-dev
      - libiberty-dev
      - python3
      - python3-pip

language: bash

matrix:
  include:
    - os: osx
      osx_image: xcode10
      rvm: system
  fast_finish: true

env:
  global:
    - CODECOV_TOKEN=4bd3d3ee-ecc8-4130-90d7-276626099dc4
    - PATH=${PATH}:${HOME}/kcov/bin

before_install:
- wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz
- /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

install:
- brew install awscli jq && pip3 install -U pip codecov pip && mkdir -p coverage

script:
- coverage run awscli.sh

after_success:
- bash <(curl -s https://codecov.io/bash)
