lang: en-US
title: AWS CLI Aliases
baseurl: "/awscli-aliases"  # the subpath of your site, e.g. /blog
url: "laniksj.github.io"  # the base hostname & protocol for your site, e.g. http://example.com
author:
  name: LanikSJ
  twitter: laniksj
description: "AWS CLI Aliases to make your life easier"
favicon: favicon.ico

# social links
twitter_username: laniksj
github_username:  LanikSJ

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# Build settings
markdown: kramdown

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
