name: CI
on: pull_request
jobs:
  Test-AWSCLI:
    runs-on: macOS-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Install & Generate Coverage
      run: |
        export PATH="/usr/local/opt/ccache/libexec:${HOME}/kcov/bin:$PATH"
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
        brew install jq kcov && kcov coverage awscli.sh
        bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: 4bd3d3ee-ecc8-4130-90d7-276626099dc4
