name: CI
on: push
jobs:
  Test-AWSCLI:
    runs-on: macOS-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v1
    - name: Set Path
      run: export PATH="/usr/local/opt/ccache/libexec:${HOME}/kcov/bin:$PATH"
    - name: Homebrew Install
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    - name: Install AWS CLI & Kcov
      run: brew install jq kcov
    - name: Generate Coverage
      run: kcov coverage awscli.sh
    - name: Upload Coverage
      run: bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: 4bd3d3ee-ecc8-4130-90d7-276626099dc4
