name: shiftleft-analysis

on: pull_request

jobs:
  scan-build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Perform Scan
      uses: ShiftLeftSecurity/scan-action@master
      env:
        WORKSPACE: ""
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SCAN_AUTO_BUILD: true
      with:
        output: reports
        type: "credscan,bash"
    
    - name: Upload report
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: reports
